### ISSUE TITLE
Jävel eller Idiot?

### ISSUE THREAD

**Issue by kodpappa** [bjorne/git-pa-svenska#19]
Låter inte det lite konstigt med 'Jävel'. Ett bättre förslag vore 'Idiot' tycker jag. I övrigt gillar jag skarpt initiativet.

**Comment by gabrielf** [comment]
En fördel med idiot är att det låter bättre i sammansatta ord: idiotvalv = git repo (jag gillar valv bättre än förvaring)

**Comment by atorstling** [comment]
Efter att ha gjort lite research röstar jag för fåne, tölp eller kuf.

**Comment by kaj** [comment]
Fån (som i "ditt fån!") kanske är vettigt?  Då har man sin kod i ett fånarkiv (git repository), kanske på fånnavet (github).  Tölp och kuf som @atorstling förelsår är också bra.

**Comment by mattihjelm** [comment]
När jag läst den här: https://en.wikipedia.org/wiki/Git_(slang)
Kommer jag även tänka på "dummer", eller bara "dum"
